"""update logging model

Revision ID: 1190ace3a3da
Revises: 8f0c6162a0a4
Create Date: 2021-11-10 14:15:11.477442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1190ace3a3da'
down_revision = '8f0c6162a0a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
