"""update passender_car model

Revision ID: 1f10f8a79c57
Revises: efea7a3a2cf4
Create Date: 2021-10-27 18:53:05.568551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f10f8a79c57'
down_revision = 'efea7a3a2cf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('passenger_car_images', sa.Column('passenger_car_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'passenger_car_images', 'passenger_car', ['passenger_car_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'passenger_car_images', type_='foreignkey')
    op.drop_column('passenger_car_images', 'passenger_car_id')
    # ### end Alembic commands ###
