"""add commercial car image

Revision ID: 6584a57792a8
Revises: 1e0dfa8c9adf
Create Date: 2021-11-12 10:49:29.243979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6584a57792a8'
down_revision = '1e0dfa8c9adf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commercial_images', sa.Column('commercial_id', sa.Integer(), nullable=True))
    op.drop_constraint('commercial_images_commercial__id_fkey', 'commercial_images', type_='foreignkey')
    op.create_foreign_key(None, 'commercial_images', 'commercial', ['commercial_id'], ['id'])
    op.drop_column('commercial_images', 'commercial__id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commercial_images', sa.Column('commercial__id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'commercial_images', type_='foreignkey')
    op.create_foreign_key('commercial_images_commercial__id_fkey', 'commercial_images', 'commercial', ['commercial__id'], ['id'])
    op.drop_column('commercial_images', 'commercial_id')
    # ### end Alembic commands ###
