"""delete datetime

Revision ID: 6ce3d04d0efd
Revises: 
Create Date: 2021-12-21 19:38:04.070348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6ce3d04d0efd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commercial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('city_of_sale', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('year_of_issue', sa.String(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('mileage', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('engine', sa.String(), nullable=True),
    sa.Column('transmission_type', sa.String(), nullable=True),
    sa.Column('drive_unit', sa.String(), nullable=True),
    sa.Column('steerin_wheel', sa.String(), nullable=True),
    sa.Column('customs', sa.String(), nullable=True),
    sa.Column('availability', sa.String(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('other', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('household',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('city_of_sale', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('additionally', sa.String(), nullable=True),
    sa.Column('delivery', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('logging_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log', sa.String(), nullable=True),
    sa.Column('log_name', sa.String(), nullable=True),
    sa.Column('log_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('passenger_car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('city_of_sale', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('year_of_issue', sa.String(), nullable=True),
    sa.Column('body_type', sa.String(), nullable=True),
    sa.Column('mileage', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('engine', sa.String(), nullable=True),
    sa.Column('transmission_type', sa.String(), nullable=True),
    sa.Column('drive_unit', sa.String(), nullable=True),
    sa.Column('steering_wheel', sa.String(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('customs', sa.String(), nullable=True),
    sa.Column('availability', sa.String(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('other', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('real_estate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('city_of_sale', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('type_of_sentence', sa.String(), nullable=True),
    sa.Column('house_type', sa.String(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('series', sa.String(), nullable=True),
    sa.Column('floor', sa.String(), nullable=True),
    sa.Column('count_room', sa.String(), nullable=True),
    sa.Column('square', sa.String(), nullable=True),
    sa.Column('square_area', sa.String(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('appliances', sa.String(), nullable=True),
    sa.Column('furniture', sa.String(), nullable=True),
    sa.Column('repair', sa.String(), nullable=True),
    sa.Column('term', sa.String(), nullable=True),
    sa.Column('deposit', sa.String(), nullable=True),
    sa.Column('animal', sa.String(), nullable=True),
    sa.Column('possibilities', sa.String(), nullable=True),
    sa.Column('additionally', sa.Text(), nullable=True),
    sa.Column('stone_throw', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('spare',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('city_of_sale', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('availability', sa.String(), nullable=True),
    sa.Column('other', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('telephone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('city_of_sale', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('memory', sa.String(), nullable=True),
    sa.Column('ram', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('additionally', sa.String(), nullable=True),
    sa.Column('delivery', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('commercial_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.Column('commercial_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['commercial_id'], ['commercial.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('household_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.Column('household_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['household.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('passenger_car_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.Column('passenger_car_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['passenger_car_id'], ['passenger_car.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('real_estate_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.Column('real_estate_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['real_estate_id'], ['real_estate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('spare_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.Column('spare_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['spare_id'], ['spare.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telephone_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.Column('telephone_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['telephone_id'], ['telephone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('anonymous_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_student', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_employee', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('anonymous_name', name='users_anonymous_name_key')
    )
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.drop_table('telephone_images')
    op.drop_table('spare_images')
    op.drop_table('real_estate_images')
    op.drop_table('passenger_car_images')
    op.drop_table('household_images')
    op.drop_table('commercial_images')
    op.drop_table('telephone')
    op.drop_table('spare')
    op.drop_table('real_estate')
    op.drop_table('passenger_car')
    op.drop_table('logging_record')
    op.drop_table('household')
    op.drop_table('commercial')
    # ### end Alembic commands ###
