"""update models

Revision ID: a839e0b48254
Revises: 73cae87e5e9a
Create Date: 2021-10-25 02:28:09.974079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a839e0b48254'
down_revision = '73cae87e5e9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
