"""second

Revision ID: d43d9af9150a
Revises: a839e0b48254
Create Date: 2021-10-25 02:29:20.777286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd43d9af9150a'
down_revision = 'a839e0b48254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
