"""update passender_car model

Revision ID: efea7a3a2cf4
Revises: 
Create Date: 2021-10-27 18:46:27.078113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efea7a3a2cf4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commercial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('city_of_sale', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('year_of_issue', sa.String(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('mileage', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('engine', sa.String(), nullable=True),
    sa.Column('transmission_type', sa.String(), nullable=True),
    sa.Column('drive_unit', sa.String(), nullable=True),
    sa.Column('steerin_wheel', sa.String(), nullable=True),
    sa.Column('customs', sa.String(), nullable=True),
    sa.Column('availability', sa.String(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('other', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('passenger_car',
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('city_of_sale', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('year_of_issue', sa.String(), nullable=True),
    sa.Column('body_type', sa.String(), nullable=True),
    sa.Column('mileage', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('engine', sa.String(), nullable=True),
    sa.Column('transmission_type', sa.String(), nullable=True),
    sa.Column('drive_unit', sa.String(), nullable=True),
    sa.Column('steering_wheel', sa.String(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('customs', sa.String(), nullable=True),
    sa.Column('availability', sa.String(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('other', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('passenger_car_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('blob', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('real_estate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('city_of_sale', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('type_of_sentence', sa.String(), nullable=True),
    sa.Column('house_type', sa.String(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('series', sa.String(), nullable=True),
    sa.Column('floor', sa.String(), nullable=True),
    sa.Column('count_room', sa.String(), nullable=True),
    sa.Column('square', sa.String(), nullable=True),
    sa.Column('square_area', sa.String(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('appliances', sa.String(), nullable=True),
    sa.Column('furniture', sa.String(), nullable=True),
    sa.Column('repair', sa.String(), nullable=True),
    sa.Column('term', sa.String(), nullable=True),
    sa.Column('deposit', sa.String(), nullable=True),
    sa.Column('animal', sa.String(), nullable=True),
    sa.Column('possibilities', sa.String(), nullable=True),
    sa.Column('additionally', sa.Text(), nullable=True),
    sa.Column('stone_throw', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('spare',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('city_of_sale', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('availability', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('telephone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('price', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('city_of_sale', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('memory', sa.String(), nullable=True),
    sa.Column('ram', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('additionally', sa.String(), nullable=True),
    sa.Column('delivery', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telephone')
    op.drop_table('spare')
    op.drop_table('real_estate')
    op.drop_table('passenger_car_images')
    op.drop_table('passenger_car')
    op.drop_table('commercial')
    # ### end Alembic commands ###
